# Generated by Django 4.0.4 on 2023-03-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Story In the Redeemed Christian Church of God', max_length=500)),
                ('aboutIntro', models.CharField(default='Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line', max_length=1000)),
                ('Ourhistory', models.TextField(help_text='please make this history in three paragraphs respectively', max_length=2000)),
                ('OurhistoryP2', models.TextField(max_length=2000)),
                ('OurhistoryP3', models.TextField(max_length=2000)),
                ('ChurchImage', models.ImageField(default='church.jpg', upload_to='church_about')),
                ('ChurchImage2', models.ImageField(default='church.jpg', upload_to='church_about')),
                ('ChurchImage3', models.ImageField(default='church.jpg', upload_to='church_about')),
            ],
        ),
        migrations.CreateModel(
            name='ContactImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='contact_image')),
            ],
        ),
    ]
