# Generated by Django 4.0.4 on 2023-03-12 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('blog_description', models.TextField(max_length=4000)),
                ('blog_image', models.ImageField(default='blog.jpg', upload_to='blog')),
                ('blog_category', models.CharField(choices=[('House Fellowship', 'House Fellowship'), ('Article', 'Article'), ('Faith Clinic', 'Faith Clinic'), ('Sunday Sermon', 'Sunday Sermon'), ('Motivation', 'Motivation'), ('Hymns', 'Hymns'), ('Annaual Convention', 'Annaual Convention'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Talks', 'Talks'), ('Open Heavens', 'Open Heavens'), ('Sunday School', 'Sunday School'), ('Anniversary', 'Anniversary'), ('Digging Deep', 'Digging Deep')], default=None, max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
