# Generated by Django 4.0.4 on 2023-03-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Open Heavens', 'Open Heavens'), ('Motivation', 'Motivation'), ('Sunday School', 'Sunday School'), ('House Fellowship', 'House Fellowship'), ('Faith Clinic', 'Faith Clinic'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Talks', 'Talks'), ('Hymns', 'Hymns'), ('Anniversary', 'Anniversary'), ('Article', 'Article'), ('Annaual Convention', 'Annaual Convention'), ('Digging Deep', 'Digging Deep'), ('Sunday Sermon', 'Sunday Sermon')], default=None, max_length=300),
        ),
    ]
