# Generated by Django 4.0.4 on 2023-03-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Motivation', 'Motivation'), ('House Fellowship', 'House Fellowship'), ('Sunday Sermon', 'Sunday Sermon'), ('Article', 'Article'), ('Digging Deep', 'Digging Deep'), ('Anniversary', 'Anniversary'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Open Heavens', 'Open Heavens'), ('Annaual Convention', 'Annaual Convention'), ('Hymns', 'Hymns'), ('Faith Clinic', 'Faith Clinic'), ('Talks', 'Talks'), ('Sunday School', 'Sunday School')], default=None, max_length=300),
        ),
    ]
