# Generated by Django 4.0.4 on 2023-05-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Hymns', 'Hymns'), ('Annaual Convention', 'Annaual Convention'), ('Article', 'Article'), ('Anniversary', 'Anniversary'), ('Faith Clinic', 'Faith Clinic'), ('Digging Deep', 'Digging Deep'), ('House Fellowship', 'House Fellowship'), ('Sunday Sermon', 'Sunday Sermon'), ('Open Heavens', 'Open Heavens'), ('Sunday School', 'Sunday School'), ('Talks', 'Talks'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Motivation', 'Motivation')], default=None, max_length=300),
        ),
    ]
