# Generated by Django 4.0.4 on 2023-05-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Sunday Sermon', 'Sunday Sermon'), ('Annaual Convention', 'Annaual Convention'), ('Sunday School', 'Sunday School'), ('Faith Clinic', 'Faith Clinic'), ('Open Heavens', 'Open Heavens'), ('Anniversary', 'Anniversary'), ('Talks', 'Talks'), ('Motivation', 'Motivation'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Hymns', 'Hymns'), ('Digging Deep', 'Digging Deep'), ('Article', 'Article'), ('House Fellowship', 'House Fellowship')], default=None, max_length=300),
        ),
    ]
