# Generated by Django 4.0.4 on 2023-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Digging Deep', 'Digging Deep'), ('Talks', 'Talks'), ('Annaual Convention', 'Annaual Convention'), ('Article', 'Article'), ('Sunday Sermon', 'Sunday Sermon'), ('Sunday School', 'Sunday School'), ('Motivation', 'Motivation'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Anniversary', 'Anniversary'), ('Open Heavens', 'Open Heavens'), ('Hymns', 'Hymns'), ('Faith Clinic', 'Faith Clinic'), ('House Fellowship', 'House Fellowship')], default=None, max_length=300),
        ),
    ]
