# Generated by Django 4.0.4 on 2023-05-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Open Heavens', 'Open Heavens'), ('Hymns', 'Hymns'), ('House Fellowship', 'House Fellowship'), ('Digging Deep', 'Digging Deep'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Anniversary', 'Anniversary'), ('Motivation', 'Motivation'), ('Article', 'Article'), ('Talks', 'Talks'), ('Annaual Convention', 'Annaual Convention'), ('Faith Clinic', 'Faith Clinic'), ('Sunday School', 'Sunday School'), ('Sunday Sermon', 'Sunday Sermon')], default=None, max_length=300),
        ),
    ]
