# Generated by Django 4.0.4 on 2023-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Annaual Convention', 'Annaual Convention'), ('Sunday School', 'Sunday School'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Open Heavens', 'Open Heavens'), ('Talks', 'Talks'), ('Hymns', 'Hymns'), ('Sunday Sermon', 'Sunday Sermon'), ('Article', 'Article'), ('Anniversary', 'Anniversary'), ('Digging Deep', 'Digging Deep'), ('Faith Clinic', 'Faith Clinic'), ('House Fellowship', 'House Fellowship'), ('Motivation', 'Motivation')], default=None, max_length=300),
        ),
    ]
