# Generated by Django 4.0.4 on 2023-05-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Holy Ghost Service', 'Holy Ghost Service'), ('Anniversary', 'Anniversary'), ('Sunday Sermon', 'Sunday Sermon'), ('Talks', 'Talks'), ('Sunday School', 'Sunday School'), ('Hymns', 'Hymns'), ('Digging Deep', 'Digging Deep'), ('Open Heavens', 'Open Heavens'), ('Faith Clinic', 'Faith Clinic'), ('Article', 'Article'), ('House Fellowship', 'House Fellowship'), ('Motivation', 'Motivation'), ('Annaual Convention', 'Annaual Convention')], default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(max_length=40000),
        ),
    ]
