# Generated by Django 4.0.4 on 2023-05-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_blog_category_alter_blog_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Talks', 'Talks'), ('Motivation', 'Motivation'), ('House Fellowship', 'House Fellowship'), ('Anniversary', 'Anniversary'), ('Hymns', 'Hymns'), ('Digging Deep', 'Digging Deep'), ('Faith Clinic', 'Faith Clinic'), ('Sunday Sermon', 'Sunday Sermon'), ('Article', 'Article'), ('Annaual Convention', 'Annaual Convention'), ('Open Heavens', 'Open Heavens'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Sunday School', 'Sunday School')], default=None, max_length=300),
        ),
    ]
