# Generated by Django 4.0.4 on 2023-05-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Article', 'Article'), ('Digging Deep', 'Digging Deep'), ('House Fellowship', 'House Fellowship'), ('Annaual Convention', 'Annaual Convention'), ('Sunday Sermon', 'Sunday Sermon'), ('Open Heavens', 'Open Heavens'), ('Anniversary', 'Anniversary'), ('Talks', 'Talks'), ('Motivation', 'Motivation'), ('Hymns', 'Hymns'), ('Faith Clinic', 'Faith Clinic'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Sunday School', 'Sunday School')], default=None, max_length=300),
        ),
    ]
