# Generated by Django 4.0.4 on 2023-05-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Digging Deep', 'Digging Deep'), ('Open Heavens', 'Open Heavens'), ('Motivation', 'Motivation'), ('Article', 'Article'), ('Annaual Convention', 'Annaual Convention'), ('Faith Clinic', 'Faith Clinic'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Hymns', 'Hymns'), ('Sunday School', 'Sunday School'), ('Sunday Sermon', 'Sunday Sermon'), ('House Fellowship', 'House Fellowship'), ('Anniversary', 'Anniversary'), ('Talks', 'Talks')], default=None, max_length=300),
        ),
    ]
