# Generated by Django 4.0.4 on 2023-05-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Open Heavens', 'Open Heavens'), ('Annaual Convention', 'Annaual Convention'), ('Digging Deep', 'Digging Deep'), ('Talks', 'Talks'), ('Faith Clinic', 'Faith Clinic'), ('House Fellowship', 'House Fellowship'), ('Motivation', 'Motivation'), ('Sunday Sermon', 'Sunday Sermon'), ('Anniversary', 'Anniversary'), ('Article', 'Article'), ('Holy Ghost Service', 'Holy Ghost Service'), ('Sunday School', 'Sunday School'), ('Hymns', 'Hymns')], default=None, max_length=300),
        ),
    ]
