# Generated by Django 4.0.4 on 2023-03-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImageHomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_slider_title', models.CharField(max_length=300)),
                ('background_slider_info', models.TextField(max_length=500)),
                ('image_slider', models.ImageField(default=None, upload_to='backgroundslider')),
            ],
        ),
        migrations.CreateModel(
            name='Church_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=100)),
                ('church_mail', models.CharField(max_length=100)),
                ('church_mobile', models.CharField(max_length=100)),
                ('church_address', models.CharField(max_length=500)),
                ('church_youtube_account', models.URLField(default='https://www.youtube.com', max_length=500)),
                ('church_facebook_account', models.URLField(default='https://www.facebook.com', max_length=500)),
                ('church_twitter_account', models.URLField(default='https://www.twitter.com', max_length=500)),
                ('church_tiktok_account', models.URLField(default='https://www.tiktok.com', max_length=500)),
                ('church_instagram_account', models.URLField(default='https://www.instagram.com', max_length=500)),
                ('year_founded', models.CharField(default='2008', help_text='add year founded', max_length=300)),
                ('no_of_house_fellowship_centers', models.IntegerField(default=6)),
                ('no_of_parishes_created', models.IntegerField(default=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='org_info_image')),
            ],
        ),
        migrations.CreateModel(
            name='minister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minister_name', models.CharField(max_length=300)),
                ('minister_title', models.CharField(max_length=300)),
                ('minister_info', models.TextField(max_length=500)),
                ('minister_pic', models.ImageField(default='minister.jpg', upload_to='minister')),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(max_length=200)),
                ('program_info', models.TextField(max_length=500)),
                ('program_image', models.ImageField(default='program.jpg', upload_to='programs')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300)),
                ('project_description', models.TextField(max_length=500)),
                ('project_image', models.ImageField(default='project.jpg', upload_to='project')),
                ('project_type', models.CharField(choices=[('Provincial', 'Provincial'), ('Zone', 'Zone'), ('Regional', 'Regional'), ('Others', 'Others')], default='Zone', max_length=255)),
            ],
        ),
    ]
