# Generated by Django 4.0.4 on 2023-03-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_projects_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('Zone', 'Zone'), ('Regional', 'Regional'), ('Others', 'Others'), ('Provincial', 'Provincial')], default='Zone', max_length=255),
        ),
    ]
