# Generated by Django 4.0.4 on 2023-03-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_projects_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('Provincial', 'Provincial'), ('Regional', 'Regional'), ('Others', 'Others'), ('Zone', 'Zone')], default='Zone', max_length=255),
        ),
    ]
