# Generated by Django 4.0.4 on 2023-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_projects_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('Others', 'Others'), ('Regional', 'Regional'), ('Zone', 'Zone'), ('Provincial', 'Provincial')], default='Zone', max_length=255),
        ),
    ]
