# Generated by Django 4.0.4 on 2023-05-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_projects_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Provincial', 'Provincial'), ('Others', 'Others'), ('Zone', 'Zone')], default='Zone', max_length=255),
        ),
    ]
