# Generated by Django 4.0.4 on 2023-05-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_projects_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Zone', 'Zone'), ('Others', 'Others'), ('Provincial', 'Provincial')], default='Zone', max_length=255),
        ),
    ]
